// Generates src/embedded.js: the files the CLI needs at runtime that would
// otherwise be read from the source tree (the Windows launcher template and
// the web UI), so a single compiled binary carries them. Run before
// `npm run build:bin`; the output is committed so plain `node bin/dupe.js`
// and the binary behave the same.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const files = {
  'win32-launcher.cs': path.join(root, 'src', 'platform', 'win32-launcher.cs'),
  'docs/index.html': path.join(root, 'docs', 'index.html'),
  'docs/dupe-image.js': path.join(root, 'docs', 'dupe-image.js'),
  'docs/android.md': path.join(root, 'docs', 'android.md'),
  'docs/ios.md': path.join(root, 'docs', 'ios.md'),
};
const out = ['// Generated by scripts/build-embed.js — do not edit.', 'export const EMBEDDED = {'];
for (const [key, file] of Object.entries(files)) {
  out.push(`  ${JSON.stringify(key)}: ${JSON.stringify(fs.readFileSync(file, 'utf8'))},`);
}
out.push('};', '');
const target = path.join(root, 'src', 'embedded.js');
fs.writeFileSync(target, out.join('\n'));
console.log(`wrote ${path.relative(root, target)} (${(fs.statSync(target).size / 1024).toFixed(1)} KB, ${Object.keys(files).length} files)`);
