// Bundles the dependency-free image modules into one browser ES module,
// docs/dupe-image.js, by concatenating them behind the Node shims. No
// bundler: the modules only import each other and node:zlib.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const order = ['color.js', 'png.js', 'ico.js', 'icns.js', 'resize.js', 'recolor.js'];
const parts = [
  '// Generated by scripts/build-web.js — do not edit. Source: src/image/*.js\n',
  fs.readFileSync(path.join(root, 'web', 'shim.js'), 'utf8'),
];
for (const name of order) {
  let src = fs.readFileSync(path.join(root, 'src', 'image', name), 'utf8');
  src = src.replace(/^import .*?;\s*$/gm, '');
  parts.push(`\n// ---- ${name}\n${src}`);
}
// The palette module, minus its store/Node imports.
let palette = fs.readFileSync(path.join(root, 'src', 'palette.js'), 'utf8').replace(/^import .*?;\s*$/gm, '');
parts.push(`\n// ---- palette.js\n${palette}`);
const out = path.join(root, 'docs', 'dupe-image.js');
fs.writeFileSync(out, parts.join('\n'));
console.log(`wrote ${path.relative(root, out)} (${(fs.statSync(out).size / 1024).toFixed(1)} KB)`);
